version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main:
      ./cmd/dartboard
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    hooks:
      pre:
        - ./download-vendored-bin.sh

archives:
  - files:
      - LICENSE
      - README.md
      - darts/*
